# Generated by Django 4.0.1 on 2022-02-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecom_Dress',
            new_name='Ecom_Chair',
        ),
    ]
