# Generated by Django 4.0.1 on 2022-02-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_customer_reg_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_reg',
            old_name='name',
            new_name='username',
        ),
    ]
