# Generated by Django 4.0.1 on 2022-02-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_ecom_dining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_dining',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
