# Generated by Django 4.0.1 on 2022-02-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_ecom_sofa_alter_ecom_chair_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecom_sofa',
            new_name='Ecom_Armchairs',
        ),
    ]
