# Generated by Django 4.0.1 on 2022-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0015_rename_ecom_sofa_ecom_armchairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_armchairs',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
