# Generated by Django 4.0.1 on 2022-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_alter_ecom_armchairs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_chair',
            name='image',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
