# Generated by Django 4.0.1 on 2022-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_alter_ecom_chair_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_chair',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
